### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by bpappin** [wajahatkarim3/Flippable#12]
It looks like the compose dependencies are very out of date.

we are currently at 1.5.5 but this lib is still depending on 1.1 which has breaking changes between them.

**Comment by wajahatkarim3** [comment]
Thank you for creating issue @bpappin . I have updated the deps as per followin

```
Compose Version = 1.5.4
Kotlin Version = 1.9.20
Coroutine = 1.5.4
kotlinCompilerExtensionVersion = 1.5.4
agpVersion = 7.4.2
Gradle wrapper = 7.6
```

Hope this fixes your breaking issues.

**Comment by bpappin** [comment]
I'll have to try it in the new year.
The issue I think was that some of the animation classes had changed.

What release version will this be in?

**Comment by wajahatkarim3** [comment]
@bpappin It's version [1.5.4 release](https://github.com/wajahatkarim3/Flippable/releases/tag/1.5.4)
